import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'sf_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'account_type', type: 'string', isIndexed: true },
        { name: 'channel', type: 'string' },
        { name: 'territory_id', type: 'string', isIndexed: true },
        { name: 'contact_name', type: 'string' },
        { name: 'contact_title', type: 'string' },
        { name: 'contact_phone', type: 'string' },
        { name: 'address_street', type: 'string' },
        { name: 'address_city', type: 'string' },
        { name: 'address_state', type: 'string' },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'last_order_date', type: 'number', isOptional: true },
        { name: 'last_visit_date', type: 'number', isOptional: true },
        { name: 'days_since_last_order', type: 'number' },
        { name: 'ytd_revenue', type: 'number' },
        { name: 'needs_attention', type: 'boolean', isIndexed: true },
        { name: 'synced_at', type: 'number' },
        { name: 'is_archived', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'sf_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'unit', type: 'string' },
        { name: 'unit_label', type: 'string' },
        { name: 'price_per_unit', type: 'number' },
        { name: 'supplier_id', type: 'string' },
        { name: 'sku_code', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'image_url', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'sf_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'account_sf_id', type: 'string' },
        { name: 'rep_id', type: 'string', isIndexed: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'order_date', type: 'number' },
        { name: 'delivery_date', type: 'number', isOptional: true },
        { name: 'total_amount', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'sync_attempts', type: 'number' },
        { name: 'created_offline', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_lines',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'product_sf_id', type: 'string' },
        { name: 'product_name', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'unit_price', type: 'number' },
        { name: 'line_total', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'visits',
      columns: [
        { name: 'sf_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'account_sf_id', type: 'string' },
        { name: 'rep_id', type: 'string', isIndexed: true },
        { name: 'visit_date', type: 'number', isIndexed: true },
        { name: 'duration_minutes', type: 'number', isOptional: true },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'raw_transcript', type: 'string', isOptional: true },
        { name: 'ai_insight', type: 'string', isOptional: true },
        { name: 'insight_feedback', type: 'string', isOptional: true },
        { name: 'order_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'sync_attempts', type: 'number' },
        { name: 'created_offline', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'label_prints',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isOptional: true },
        { name: 'template_type', type: 'string' },
        { name: 'product_name', type: 'string' },
        { name: 'printer_serial', type: 'string', isOptional: true },
        { name: 'printed_at', type: 'number' },
        { name: 'zpl_snapshot', type: 'string' },
        { name: 'sync_status', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'operation_type', type: 'string', isIndexed: true },
        { name: 'entity_type', type: 'string', isIndexed: true },
        { name: 'entity_id', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'attempts', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'processed_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'memories',
      columns: [
        { name: 'rep_id', type: 'string', isIndexed: true },
        { name: 'account_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'confidence', type: 'number' },
        { name: 'source', type: 'string' },
        { name: 'use_count', type: 'number' },
        { name: 'last_used_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'sf_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'feedback_events',
      columns: [
        { name: 'rep_id', type: 'string', isIndexed: true },
        { name: 'account_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'event_type', type: 'string', isIndexed: true },
        { name: 'ai_output', type: 'string' },
        { name: 'user_correction', type: 'string', isOptional: true },
        { name: 'context_json', type: 'string' },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'synthesized', type: 'boolean', isIndexed: true },
      ],
    }),
    // Roles & Admin doc §12 — additive Day 1 table
    tableSchema({
      name: 'permissions',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'roles_json', type: 'string' },
        { name: 'primary_role', type: 'string', isIndexed: true },
        { name: 'custom_perms_json', type: 'string' },
        { name: 'fetched_at', type: 'number' },
      ],
    }),
  ],
});
